# Generated by Django 3.1.7 on 2021-03-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210308_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desciption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
